task_track:
    resource: "@TaskTrackBundle/Resources/config/routing.yml"
    prefix:   /

login_check:
    path:     /api/login_check
    methods:  [POST]

supervisor_login_check:
    path:     /api/supervisor/login_check
    methods:  [POST]

admin_login_check:
    path:     /api/admin/login_check
    methods:  [POST]


app:
    resource: '@AppBundle/Controller/'
    type: annotation
