security:
    encoders:
        TaskTrackBundle\Entity\User:
            algorithm: bcrypt

    providers:
        entity_provider:
            entity:
                class: TaskTrackBundle:User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            form_login:
                check_path: /api/login_check
                require_previous_session: false
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure


        register:
            pattern:  ^/api/register
            stateless: true
            anonymous: true

        api:
            pattern:  ^/api
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                    - app.jwt_token_authenticator
        
        refresh:
            pattern:  ^/api/token/refresh
            stateless: true
            anonymous: true
        
        
    access_control:
        - { path: ^/api/token/refresh, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/token/revoke, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/admin, roles: [ROLE_SUPERADMIN] }
        - { path: ^/api/supervisor, roles: [ROLE_ADMIN] }
        - { path: ^/api/auth, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/logout, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api, roles: [ROLE_USER] }
        