# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        fos_userbundle:
            id: fos_user.user_provider.username_email
        jwt:
            lexik_jwt:
                class: TaskTrackBundle\Entity\User
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        #main:
        #    anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
        
        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            form_login:
                check_path:               /api/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        api:
            pattern:   ^/api/(?!(register)).*$
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
                provider: jwt
                    
    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: POST }
        - { path: ^/api/register, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: POST }
        - { path: ^/api/admin/login, ip: 127.0.0.1, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: POST }
        - { path: ^/api/supervisor/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: POST }
        - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY, ROLE_TRAINEE ] }
        - { path: ^/api/admin, ip: 127.0.0.1, roles: [ IS_AUTHENTICATED_FULLY, ROLE_ADMIN ]}
        - { path: ^/api/supervisor, roles: [ IS_AUTHENTICATED_FULLY, ROLE_SUPERVISOR ] }
            
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        
    
