task_track_homepage:
    path:     /
    defaults: { _controller: TaskTrackBundle:Default:index }
    methods: [POST]
    
register:
    path: /api/register
    defaults: { _controller: TaskTrackBundle:User:register }
    methods: [POST]
    
register_supervisor:
    path: /api/admin/register_supervisor
    defaults: { _controller: TaskTrackBundle:User:registerSupervisor }
    methods: [POST]

check:
    path: /api
    defaults: { _controller: TaskTrackBundle:User:api }
    
get_name:
    path: /api/get_user_info
    defaults: { _controller: TaskTrackBundle:User:getUserInfo }
    methods: [POST]
