task_track_homepage:
    path:     /
    defaults: { _controller: TaskTrackBundle:Default:index }
    methods: [POST]
    
about_us_page:
    path: /about
    defaults: { _controller: TaskTrackBundle:AboutPage:aboutUs }
    methods: [GET]

revoke_refresh_token:
    path: /api/logout
    defaults: { _controller: TaskTrackBundle:User:logout }
    methods: [DELETE]

register:
    path: /api/register
    defaults: { _controller: TaskTrackBundle:User:registerTrainee }
    methods: [POST]
    
register_supervisor:
    path: /api/admin/supervisors
    defaults: { _controller: TaskTrackBundle:User:registerSupervisor }
    methods: [POST]
    
get_supervisors:
    path: /api/admin/supervisors
    defaults: { _controller: TaskTrackBundle:User:getAllSupervisors }
    methods: [GET]
    
get_trainees:
    path: /api/{role}/trainees
    defaults: { _controller: TaskTrackBundle:User:getAllTrainees, page:1 }
    methods: [GET]
    requirements:
        role: '(admin|supervisor)'

check:
    path: /api
    defaults: { _controller: TaskTrackBundle:User:api }
    
get_users:
    path: /api/admin/users
    defaults: { _controller: TaskTrackBundle:User:getFilteredUsers }
    methods: [GET]

#get_trainees:
#    path: /api/supervisor/users
#    defaults: { _controller: TaskTrackBundle:User:getAllTrainees }
#    methods: [GET]

get_user:
    path: /api/{role}/{type}/{id}
    defaults: { _controller: TaskTrackBundle:User:getUser }
    methods: [GET]
    requirements:
        id: '\d+'
        type: 'users|supervisors|trainees'
        role: 'admin|supervisor'


get_user_tasks:
    path: /api/supervisor/trainees/{user_id}/tasks
    defaults: { _controller: TaskTrackBundle:Task:getUserTasks }
    requirements:
        user_id: '\d+'
    methods: [GET]
    
    
 
get_my_tasks:
    path: /api/tasks/suggested_order
    defaults: { _controller: TaskTrackBundle:Task:getMyTasks}
    methods: [GET]
    
get_my_recommended_tasks:
    path: /api/tasks/recommended
    defaults: { _controller: TaskTrackBundle:Task:getMyRecommendedTasks }
    methods: [GET]
        
get_supervisor_challenges:
    path: /api/supervisor/challenges
    defaults: { _controller: TaskTrackBundle:Challenge:getMyChallenges }
    methods: [GET]
    
create_new_challenge:
    path: /api/supervisor/challenges
    defaults: { _controller: TaskTrackBundle:Challenge:createNewChallenge }
    methods: [POST]
    
delete_user:
    path: /api/admin/users/{id}
    defaults: { _controller: TaskTrackBundle:User:deleteUser }
    requirements:
        id: '\d+'
    methods: [DELETE]
    
get_authenticated:
    path: /api/{role}
    defaults: { _controller: TaskTrackBundle:User:getAuthenticatedUser }
    methods: [GET]
    requirements:
        role: "(admin|supervisor|user)"

get_user_details_admin:
    path: /api/admin/users/{id}
    defaults: { _controller: TaskTrackBundle:User:getUser }
    methods: [GET]
    requirements:
        id: '\d+'
    
update_user:
    path: /api/{role}
    defaults: { _controller: TaskTrackBundle:User:updateUserInfo }
    methods: [PUT]
    requirements:
        role: "(admin|supervisor|user)"
        
#trainee_challenges_register:
#    path: /api/supervisor/trainees/{trainee_id}/challenges
#    defaults: { _controller: TaskTrackBundle:User:getMyChallenges }
#    methods: [GET]
#    requirements:
#        trainee_id: '\d+'

new_task:
    path: /api/supervisor/trainees/{user_id}/challenges
    defaults: { _controller: TaskTrackBundle:Task:createNewTask }
    methods: [POST]
    requirements:
        trainee_id: '\d+'
        
update_challenge:
    path: /api/supervisor/challenges
    defaults: { _controller: TaskTrackBundle:Challenge:updateChallenge }
    methods: [PUT]
    
add_challenge_child:
    path: /api/supervisor/challenges
    defaults: { _controller: TaskTrackBundle:Challenge:addChallengeChild }
    methods: [PATCH]
    
get_supervisor_filtered_tasks:
    path: /api/supervisor/tasks
    defaults: { _controller: TaskTrackBundle:Task:getSupervisorFilteredTasks }
    methods: [GET]
        
get_trainee_filtered_tasks:
    path: /api/tasks
    defaults: { _controller: TaskTrackBundle:Task:getTraineeFilteredTasks }
    methods: [GET]
        
get_unassigned_challenges:
    path: /api/supervisor/trainees/{user_id}/challenges
    defaults: { _controller: TaskTrackBundle:Challenge:getUnassignedChallenges }
    methods: [GET]

get_challenge_children:
    path: /api/supervisor/challenges/{challenge_id}/dependents
    methods: [GET]
    defaults: { _controller: TaskTrackBundle:Challenge:getChallengeChildren }
        

delete_supervisor_challenge:
    path: /api/supervisor/challenges
    methods: [DELETE]
    defaults: { _controller: TaskTrackBundle:Challenge:deleteChallenge }
    
delete_user_task:
    path: /api/supervisor/trainees/{user_id}/tasks
    methods: [DELETE]
    defaults: { _controller: TaskTrackBundle:User:deleteTask }
    requirements: 
        user_id: '\d+'
        
update_task_score:
    path: /api/supervisor/trainees/{user_id}/tasks/{task_id}/score
    methods: [PUT]
    defaults: { _controller: TaskTrackBundle:Task:updateUserTaskScore }
    requirements:
        user_id: '\d+'
        task_id: '\d+'
    
update_task_done:
    path: /api/supervisor/trainees/{user_id}/tasks/{task_id}/done
    methods: [PUT]
    defaults: { _controller: TaskTrackBundle:Task:updateTaskDone }
    requirements:
        user_id: '\d+'
        task_id: '\d+'
        
update_task_duration:
    path: /api/supervisor/trainees/{user_id}/tasks/{task_id}/duration
    methods: [PUT]
    defaults: { _controller: TaskTrackBundle:Task:updateUserTaskDuration }
    requirements:
        user_id: '\d+'
        task_id: '\d+'
        
get_single_challenge:
    path: /api/supervisor/challenges/{challenge_id}
    methods: [GET]
    defaults: { _controller: TaskTrackBundle:Challenge:getSingleChallenge }
    
toggle_task_in_progress:
    path: /api/tasks/{task_id}/in_progress/toggle
    methods: [PUT]
    defaults: { _controller: TaskTrackBundle:Task:toggleTaskInProgress }