task_track_homepage:
    path:     /
    defaults: { _controller: TaskTrackBundle:Default:index }
    methods: [POST]
    
about_us_page:
    path: /about
    defaults: { _controller: TaskTrackBundle:AboutPage:aboutUs }
    methods: [GET]

revoke_refresh_token:
    path: /api/logout
    defaults: { _controller: TaskTrackBundle:User:logout }
    methods: [GET]

register:
    path: /api/register
    defaults: { _controller: TaskTrackBundle:User:registerTrainee }
    methods: [POST]
    
register_supervisor:
    path: /api/admin/supervisors
    defaults: { _controller: TaskTrackBundle:User:registerSupervisor }
    methods: [POST]
    
get_supervisors:
    path: /api/admin/supervisors
    defaults: { _controller: TaskTrackBundle:User:getAllSupervisors }
    methods: [GET]
    
get_trainees:
    path: /api/{role}/trainees
    defaults: { _controller: TaskTrackBundle:User:getAllTrainees }
    methods: [GET]
    requirements:
        role: '(admin|supervisor)'

check:
    path: /api
    defaults: { _controller: TaskTrackBundle:User:api }
    
get_users:
    path: /api/admin/users/{page}
    defaults: { _controller: TaskTrackBundle:User:getFilteredUsers, page:1 }
    methods: [GET]
    requirements:
        page: '\d*'

#get_trainees:
#    path: /api/supervisor/users
#    defaults: { _controller: TaskTrackBundle:User:getAllTrainees }
#    methods: [GET]

get_user:
    path: /api/admin/{type}/{id}
    defaults: { _controller: TaskTrackBundle:User:getUser }
    methods: [GET]
    requirements:
        id: '\d+'
        type: 'users|supervisors|trainees'


get_user_tasks:
    path: /api/{role}/trainees/{user_id}/tasks
    defaults: { _controller: TaskTrackBundle:User:getUserTasks }
    requirements:
        user_id: '\d+'
        role: '(admin|supervisor)'
    methods: [GET]
 
get_my_tasks:
    path: /api/tasks
    defaults: { _controller: TaskTrackBundle:User:getMyTasks }
    methods: [GET]
    
get_supervisor_challenges:
    path: /api/supervisor/challenges/{page}
    defaults: { _controller: TaskTrackBundle:User:getMyChallenges, page: 1 }
    methods: [GET]
    requirements:
        page: '\d*'
    
create_new_challenge:
    path: /api/supervisor/challenges
    defaults: { _controller: TaskTrackBundle:User:createNewChallenge }
    methods: [POST]
    
delete_user:
    path: /api/admin/users
    defaults: { _controller: TaskTrackBundle:User:deleteUser }
    requirements:
        id: '\d+'
    methods: [DELETE]
    
get_authenticated:
    path: /api/{role}
    defaults: { _controller: TaskTrackBundle:User:getAuthenticatedUser }
    methods: [GET]
    requirements:
        role: "(admin|supervisor|user)"

get_user_details_admin:
    path: /api/admin/users/{id}
    defaults: { _controller: TaskTrackBundle:User:getUser }
    methods: [GET]
    requirements:
        id: '\d+'
    
update_user:
    path: /api/{role}
    defaults: { _controller: TaskTrackBundle:User:updateUserInfo }
    methods: [PUT]
    requirements:
        role: "(admin|supervisor|trainee)"
        
trainee_challenges_register:
    path: /api/supervisor/trainees/{trainee_id}/challenges
    defaults: { _controller: TaskTrackBundle:User:getMyChallenges }
    methods: [GET]
    requirements:
        trainee_id: '\d+'

new_task:
    path: /api/supervisor/trainees/{user_id}/challenges
    defaults: { _controller: TaskTrackBundle:User:createNewTask }
    methods: [POST]
    requirements:
        trainee_id: '\d+'
        
update_challenge:
    path: /api/supervisor/challenges
    defaults: { _controller: TaskTrackBundle:User:updateChallenge }
    methods: [PUT]
    
add_challenge_child:
    path: /api/supervisor/challenges
    defaults: { _controller: TaskTrackBundle:User:addChallengeChild }
    methods: [PATCH]
    
get_filtered_tasks:
    path: /api/supervisor/tasks/{page}
    defaults: { _controller: TaskTrackBundle:User:getFilteredTasks, page: 1 }
    methods: [GET]
    requirements: 
        page: '\d*'
    
