services:
#    task_track.example:
#        class: TaskTrackBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    services.user_service:
        class: TaskTrackBundle\Service\UserService
        arguments: 
            - '@doctrine.orm.entity_manager'
            - '@jms_serializer'
            
    services.task_service:
        class: TaskTrackBundle\Service\TaskService
        arguments: 
            - '@doctrine.orm.entity_manager'
            - '@jms_serializer'
            
    services.challenge_service:
        class: TaskTrackBundle\Service\ChallengeService
        arguments: 
            - '@doctrine.orm.entity_manager'
            - '@jms_serializer'
            
    services.form_service:
        class: TaskTrackBundle\Service\FormService
            
    services.graph_service.kosaraju:
        class: TaskTrackBundle\Graphs\Kosaraju
        
    services.filters.entity_filter:
        class: TaskTrackBundle\Filters\EntityConcrete
        
    services.filters.entity_filter.filter_by_creation_date:
        class: TaskTrackBundle\Filters\FilterByCreationDate
        
    services.filters.entity_filter.filter_by_description:
        class: TaskTrackBundle\Filters\FilterByDescription
        
    services.filters.entity_filter.filter_by_done:
        class: TaskTrackBundle\Filters\FilterByDone
        
    services.filters.entity_filter.filter_by_duration:
        class: TaskTrackBundle\Filters\FilterByDuration
    
    services.filters.entity_filter.filter_by_seconds:
        class: TaskTrackBundle\Filters\FilterBySeconds
    
    services.filters.entity_filter.filter_by_score:
        class: TaskTrackBundle\Filters\FilterByScore
        
    services.filters.entity_filter.filter_by_title:
        class: TaskTrackBundle\Filters\FilterByTitle
        
    services.filters.entity_filter.filter_by_update_date:
        class: TaskTrackBundle\Filters\FilterByUpdateDate
        
    services.filters.entity_filter.filter_by_supervisor:
        class: TaskTrackBundle\Filters\FilterBySupervisor
        
    services.filters.entity_filter.filter_by_user:
        class: TaskTrackBundle\Filters\FilterByUser
        
    services.filters.entity_filter.factory:
        class: TaskTrackBundle\Filters\Factory
    
    user_agent_subscriber:
        class: TaskTrackBundle\EventListener\UserAgentSubscriber
        tags:
            - { name: kernel.event_subscriber }
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@security.token_storage'
            
    helpers.paginator_helper:
        class: TaskTrackBundle\Helpers\PaginatorHelper
    
    helpers.form_helper:
        class: TaskTrackBundle\Helpers\FormHelper

    exception_subscriber:
        class: TaskTrackBundle\EventListener\ExceptionListener
        tags:
           - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }