#TaskTrackBundle\Entity\User:
#    properties:
#        name:
#            - NotBlank:
#                message: Name cannot be empty.
#            - NotNull: 
#                message: Name cannot be null
#            - Length: 
#                min: 3
#                max: 100
#                exactMessage: Name should be exactly {{ limit }}.
#        password:
#            - NotBlank:
#                message: Password cannot be empty.
#            - NotNull: 
#                message: Password cannot be null.
#        email: 
#            - NotBlank:
#                message: Email cannot be blank.
#            - NotNull:
#                message: Email cannot be null.
#            - Email:
#                message: "{{ value }} is not a valid email."
#                