AppBundle\Entity\User:
    properties:
        name:
            - NotBlank: ~
            - Length: 
                min: 3
                max: 100
        email:
            - Email:
                message: The email "{{ value }}" isn't valid
                checkMX: true
        password:
            - Length:
                min: 6
                max: 100
