<?php

namespace TaskTrackBundle\Repository;

/**
 * AboutPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AboutPageRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPageContent() {
        $pageContent = $this->createQueryBuilder("ap")
                ->select()
                ->orderBy("ap.section", "ASC")
                ->getQuery()
                ->getResult();
        return $pageContent;
    }
}
