<?php

namespace TaskTrackBundle\Repository;

use TaskTrackBundle\Entity\Blacklist;

/**
 * BlacklistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlacklistRepository extends \Doctrine\ORM\EntityRepository
{
    public function blackListToken($token) {
        $em = $this->getEntityManager();
        $blackList = new Blacklist;
        $blackList->setToken($token);
        $em->persist($blackList);
        $em->flush();
    }
    
    public function isBlackListed($token) {
        $blackListed = $this->findOneBy(["token" => $token]) instanceof Blacklist;
        return $blackListed;
    }
}
