<?php

namespace TaskTrackBundle\Repository;

use TaskTrackBundle\Entity\Challenge;

/**
 * ChallengeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChallengeRepository extends \Doctrine\ORM\EntityRepository
{
    public function addNewChallenge($user, $parent, $duration, $description) {
        $em = $this->getEntityManager();
        
        $challenge = new Challenge;
        $challenge->setParent($parent);
        $challenge->setDuration($duration);
        $challenge->setDescription($description);
        $challenge->setSupervisor($user);
        
        $em->persist($challenge);
        $em->flush();
    }
    
    public function getChallenge($id) {
        return $this->findOneById($id);
    }
}
