<?php

namespace TaskTrackBundle\Repository;

use TaskTrackBundle\Entity\Challenge;

/**
 * ChallengeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChallengeRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function addNewChallenge($user, $title, $duration, $description) {
        $em = $this->getEntityManager();
        $challenge = new Challenge;
        $challenge->setDuration($duration);
        $challenge->setDescription($description);
        $challenge->setTitle($title);
        $challenge->setSupervisor($user);
        $em->persist($challenge);
        $em->flush();
        
    }
    
    public function getChallenge($id) {
        return $this->findOneById($id);
    }
    
    public function updateChallenge($challenge_id, $data) {
        $q = $this->createQueryBuilder("c")
                ->update();
        
        foreach($data as $key => $value) {
            $q = $q->set("c." . $key, "'$value'");
        }
        
        $q->where("c.id = :challenge_id")
                ->setParameter("challenge_id", $challenge_id)
                ->getQuery()->execute();
    }
    
    public function makeConnection($parent_id, $child_id) {
        $em = $this->getEntityManager();
        $parent = $this->getChallenge($parent_id);
        $child = $this->getChallenge($child_id);
        $child->addParent($parent);
        $parent->addChild($child);
        $em->persist($child);
        $em->persist($parent);
        $em->flush();
    }
    
    public function getUserChallenges($user_id, $paginator, $page, $itemsPerPage, $count = false) {
        $qb = $this->createQueryBuilder("c");
        $challenges = $qb
                ->select()
                ->where("c.supervisor = :user_id")
                ->setParameter("user_id", $user_id);
        
        if($count) {
            return $paginator->getPages($challenges, $itemsPerPage);
        }
        else {
            return $paginator->getResult($challenges, $page, $itemsPerPage);
        }
        
    }
    
    public function getChallengeBySupervisor($supervisor_id, $challenge_id) {
        $challenge = $this->createQueryBuilder("c")
                ->select()
                ->where("c.supervisor = :supervisor_id and c.id = :challenge_id") 
                ->setParameter("supervisor_id", $supervisor_id)
                ->setParameter("challenge_id", $challenge_id)
                ->getQuery()->getResult();
        return $challenge;
    }
}
