<?php

namespace TaskTrackBundle\Repository;

/**
 * TaskUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskUserRepository extends \Doctrine\ORM\EntityRepository
{
}
