<?php

namespace TaskTrackBundle\Repository;

use TaskTrackBundle\Entity\User;
use Symfony\Component\Config\Definition\Exception\Exception;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function checkIfRegistered($username, $email) {
        $user = $this->createQueryBuilder('u')
                ->where("u.username = :username")
                ->orWhere("u.email = :email")
                ->setParameters([
                    "email" => $email,
                    "username" => $username
                ])->getQuery()->getArrayResult();
        return $user;
    }
    
    public function addNewUser($name, $username, $email, $password, $role) {
        $em = $this->getEntityManager();
        $user = new User();
        $user->setUsername($username)
                ->setName($name)
                ->setRole($role)
                ->setPassword($password)
                ->setEmail($email);
        $em->persist($user);
        $em->flush();
    }
    
    public function deleteUser($id) {
        $user = $this->findOneById($id);
        $em = $this->getEntityManager();
        $em->remove($user);
        $em->flush();
    }
    
    public function updateUser($user, $data) {
        $q = $this->createQueryBuilder("u")->update();
        foreach($data as $key => $value) {
            $q = $q->set("u." . $key, "'$value'");
        }
        return $q->where("u.id = :id")->setParameter("id", $user->getId())->getQuery()->execute();
    }
    
    public function getAllUsers() {
        $users = $this->createQueryBuilder("q")->select()->getQuery()->getArrayResult();
        
        return $users;
    }
    
    public function getUsersByRole($role, $paginator, $page, $itemsPerPage, $count = false) {
        $users = $this->createQueryBuilder("u")
                ->select()
                ->where("u.role = :role")
                ->setParameter("role", $role);
        
        if($count) {
            return $paginator->getCount($users);
        }
        else {
            return $paginator->getResult($users, $page, $itemsPerPage);
        }
    }
    
    public function getUsersExceptRole($role, $paginator, $page, $itemsPerPage, $count = false) {
        $users = $this->createQueryBuilder("u")
                ->select()
                ->where("u.role != :role")
                ->setParameter("role", $role);
        if($count) {
            return $paginator->getPages($users, $itemsPerPage);
        }
        else {
            return $paginator->getResult($users, $page, $itemsPerPage);
        }
        return $users;
    }
    
    public function getUser($id) {
        
        $user = $this->createQueryBuilder("u")
                ->select()
                ->where("u.id = :id")
                ->setParameter("id", $id)
                ->getQuery()->getArrayResult();
        
        return $user;
    }
    
    public function getUserByRole($id, $role) {
        $user = $this->findOneBy(["id" => $id, "role" => $role]);
     
        return $user;
    }
    
    public function getUserChallenges($id) {
        $user = $this->findOneBy($id);
        
        return $user->getChallenges();
    }
    
    public function getUserTasks($id) {
        $user = $this->findByOne($id);
        
        
        return $user->getTasks();
    }
    
    public function getFilteredUsers($filter, $paginator, $page, $itemsPerPage, $count = false) {
        
        $qb = $this->createQueryBuilder("u")->select();
        $users = $filter->filter($qb);
        if($count) {
            $users = $paginator->getCount($users, $itemsPerPage);
        }
        else {
            $users = $paginator->getResult($users, $page, $itemsPerPage);
        }
        return $users;
    }
    
}
