<?php

namespace TaskTrackBundle\Repository;

use TaskTrackBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function checkIfRegistered($username, $email) {
        $user = $this->createQueryBuilder('u')
                ->where("u.username = :username")
                ->orWhere("u.email = :email")
                ->setParameters([
                    "email" => $email,
                    "username" => $username
                ])->getQuery()->getResult();
        return $user;
    }
    
    public function addNewUser($name, $username, $email, $password, $role) {
        $em = $this->getEntityManager();
        $user = new User();
        $user->setUsername($username)
                ->setName($name)
                ->setRole($role)
                ->setPassword($password)
                ->setEmail($email);
        $em->persist($user);
        $em->flush();
    }
    
    public function deleteUser($username) {
        $user = $this->findOne($user);
        $em = $this->getEntityManager();
        $em->getEntityManager()->remove($user);
        $em->flush();
    }
//    
//    public function updateUser($parameters, $whereCondition) {
//        $n = count($columns);
//        $q = $this->createQueryBuilder('u')
//                ->update()
//                ->setParameters($parameters)
//                ->where();
//                
//    }
    
    public function selectAllUsers() {
        $users = $this->createQueryBuilder("q")->select()->getQuery()->getResult();
        
        return $users;
    }
    
    public function selectUsersByRole($role) {
        $users = $this->selectQueryBuilder("q")
                ->select()
                ->where("u.role = :role")
                ->setParameter("role", $role)
                ->getQuery()->getResult();
        return $users;
    }
}
