TaskTrackBundle\Entity\Blacklist:
    type: entity
    table: null
    repositoryClass: TaskTrackBundle\Repository\BlacklistRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: 
        prePersist: [ setTimeStamps ]
        preUpdate: [ updateTime ]
    
    fields:
        token:
            type: string
            length: 1000  
            unique: true
            
        created_at:
            type: datetime
            
        updated_at:
            type: datetime
