TaskTrackBundle\Entity\Challenge:
    type: entity
    table: null
    
    oneToMany:
        
        tasks:
            targetEntity: Task
            mappedBy: challenge
            
    manyToOne:
        
        supervisor:
            targetEntity: User
            inversedBy: challenges
            fetch: EAGER
            joinColumn:
                name: user_id
                referencedColumnName: id
                onDelete: cascade
    
    manyToMany:
        children:
          targetEntity: Challenge
          inversedBy: parents
        
        parents:
            targetEntity: Challenge
            mappedBy: children

          
    
    repositoryClass: TaskTrackBundle\Repository\ChallengeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
                
    fields:
        title:
            type: string
        duration:
            type: integer
        description:
            type: string
        created_at:
            type: datetime
            nullable: true
        updated_at:
            type: datetime
            nullable: true
        
    lifecycleCallbacks:
        prePersist: [ setTimeStamps ]
        preUpdate: [ updateTime ]
