TaskTrackBundle\Entity\User:
    type: entity
    table: user
    
        
    
    oneToMany:
        tasks:
            targetEntity: Task
            mappedBy: user
        challenges:
            targetEntity: Challenge
            mappedBy: supervisor
            
    repositoryClass: TaskTrackBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 100
        email:
            type: string
            length: 100
            unique: true
        password:
            type: string
            length: 100
        role:
            type: integer
        created_at:
            type: datetime
        updated_at:
            type: datetime
            
    lifecycleCallbacks:
        prePersist: [ setTimeStamps ]
        preUpdate: [ updateTime ]
