api_login_check:
    path: /api/login_check

api:
    path: /api

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

login:
    resource: "@LoginBundle/Resources/config/routing.yml"
    prefix:   /

task_track:
    resource: "@TaskTrackBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
